translation-related changes, comitted ca.po

diff --git a/spun-live b/spun-live
--- a/spun-live
+++ b/spun-live
@@ -2,10 +2,11 @@
 # simple pacman update notifier
 # a very simplistic update notification script written 
 # in bash, using notify-send and kdialog. 
+TEXTDOMAIN=spun
 
 main() {
   if [[ $1 == '-h' || $1 == '--help' ]]; then
-    echo $"Simple pacman update notifier, v0.2.3"
+    echo $"Simple pacman update notifier, v0.2.4"
     echo $"Usage: spun [OPTIONS]"
     echo $"Options: "
     echo $"  -g, --gui              show the kdialog configuration GUI"
@@ -21,7 +22,7 @@ main() {
   # Check to see if the script is already running
   if [[ -r /tmp/spun/pid ]]; then
     kill -CONT $(cat "$tmpdir/pid" 2>/dev/null) 2>/dev/null && 
-      fail "spun is already running!\nonly one instance can be run at a time."
+      fail $"spun is already running!\nonly one instance can be run at a time."
   fi
   # Calculate seconds to sleep:
   [[ $waittime -le 10080 && $waittime -ge 1 ]] && 
@@ -94,7 +95,7 @@ notify() {
     grep -q " $pkg " <<< "${notified[@]}" || npkgz+=( "$pkg" ) notified+=( " $pkg " )
   done
   [[ -n "${npkgz[@]}" ]] && eval $notify $n_opts $"'There are updates available!'" \
-    $"'Updates are available for the following package(s): \n${npkgz[*]} \n\
+    "'$(gettext "Updates are available for the following package(s): \n") ${npkgz[*]} \n\
 Run \"sudo pacman -Syu\" to update.\n \
 <a href=http://www.chakra-linux.org/wiki/index.php/Pacman>Visit the Chakra wiki</a> to learn more about Pacman.'"
 }
@@ -105,7 +106,7 @@ fail() {
   exit 1
 }
 
-[[ -r /etc/spun.conf ]] && source /etc/spun.conf || fail "/etc/spun.conf cannot be found or is invalid!"
+[[ -r /etc/spun.conf ]] && source /etc/spun.conf || fail $"/etc/spun.conf cannot be found or is invalid!"
 [[ -r ~/.spunrc ]] && source ~/.spunrc || /bin/cp /etc/spun.conf ~/.spunrc
 daemon=${daemon-1} waittime=${waittime-5} notified=( )
 
